const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'public', 'locales');

const en = {
  "dashboard": "Dashboard",
  "purchase": "Purchase",
  "mandi_commission": "Purchase + Sale",
  "gate_entry": "Gate Entry",
  "arrivals": "Arrivals (Inward)",
  "purchase_bills": "Purchase Bills",
  "sales": "Sales & Billing",
  "sale_invoice": "Sale Invoice",
  "bulk_lot_sale": "Bulk Lot Sale",
  "inventory": "Stock Status",
  "commodity_master": "Commodity Master",
  "stock_status": "Stock Status",
  "payments_receipts": "Payments & Receipts",
  "trading_pl": "Trading P&L",
  "finance": "Finance",
  "finance_overview": "Finance Overview",
  "day_book": "Day Book",
  "follow_ups": "Follow-Ups",
  "cheque_mgmt": "Cheque Management",
  "gst_compliance": "Compliance",
  "balance_sheet": "Balance Sheet",
  "master_data": "Master Data",
  "crate_types": "Crate Types",
  "customers_vendors": "Customers & Vendors",
  "banks": "Banks",
  "employees": "Employees",
  "quick_actions": "Quick Actions",
  "quick_purchase": "Quick Purchase",
  "quick_sales": "Quick Sales",
  "pos": "POS",
  "returns": "Returns",
  "settings": "Settings",
  "general_settings": "General Settings",
  "team_access": "Team Access",
  "bank_details": "Bank Details",
  "branding": "Branding",
  "subscription_billing": "Subscription & Billing",
  "admin_dashboard": "Admin Dashboard",
  "tenants": "Tenants",
  "admin_billing": "Admin Billing",
  "billing_overview": "Billing Overview",
  "payment_gateways": "Payment Gateways",
  "coupons": "Coupons",
  "home": "Home",
  "inward": "Inward",
  "money": "Finance",
  "menu": "Menu",
  "hq_portal": "HQ Portal",
  "system_online": "System Online",
  "compliance": "Compliance",
  "pricing": "Pricing",
  "edition": "Edition",
  "logout": "Log Out",
  "language": "Select Language"
};

const hi = {
  ...en,
  "dashboard": "डैशबोर्ड",
  "purchase": "खरीद",
  "mandi_commission": "खरीद + बिक्री",
  "gate_entry": "गेट एंट्री",
  "arrivals": "आवक (इनवर्ड)",
  "purchase_bills": "खरीद बिल",
  "sales": "बिक्री और बिलिंग",
  "sale_invoice": "बिक्री चालान",
  "bulk_lot_sale": "थोक लॉट बिक्री",
  "inventory": "स्टॉक की स्थिति",
  "commodity_master": "कमोडिटी मास्टर",
  "stock_status": "स्टॉक की स्थिति",
  "payments_receipts": "भुगतान और रसीदें",
  "trading_pl": "व्यापार लाभ/हानि",
  "finance": "वित्त",
  "finance_overview": "वित्त अवलोकन",
  "day_book": "डे बुक",
  "follow_ups": "फॉलो-अप",
  "cheque_mgmt": "चेक प्रबंधन",
  "gst_compliance": "अनुपालन",
  "balance_sheet": "बैलेंस शीट",
  "master_data": "मास्टर डेटा",
  "crate_types": "क्रेट प्रकार",
  "customers_vendors": "ग्राहक और विक्रेता",
  "banks": "बैंक",
  "employees": "कर्मचारी",
  "quick_actions": "त्वरित क्रियाएं",
  "quick_purchase": "त्वरित खरीद",
  "quick_sales": "त्वरित बिक्री",
  "pos": "पीओएस",
  "returns": "रिटर्न",
  "settings": "सेटिंग्स",
  "general_settings": "सामान्य सेटिंग्स",
  "team_access": "टीम एक्सेस",
  "bank_details": "बैंक विवरण",
  "branding": "ब्रांडिंग",
  "subscription_billing": "सदस्यता और बिलिंग",
  "logout": "लॉग आउट",
  "language": "भाषा चुनें"
};

const mr = {
  ...en,
  "dashboard": "डॅशबोर्ड",
  "purchase": "खरेदी",
  "mandi_commission": "खरेदी + विक्री",
  "gate_entry": "गेट एंट्री",
  "arrivals": "आवक (इनवर्ड)",
  "purchase_bills": "खरेदी बिले",
  "sales": "विक्री आणि बिलिंग",
  "sale_invoice": "विक्री चलन",
  "bulk_lot_sale": "घाऊक लॉट विक्री",
  "inventory": "स्टॉक स्थिती",
  "commodity_master": "कमोडिटी मास्टर",
  "stock_status": "स्टॉक स्थिती",
  "payments_receipts": "पेमेंट आणि पावत्या",
  "trading_pl": "ट्रेडिंग नफा/तोटा",
  "finance": "वित्त",
  "finance_overview": "वित्त विहंगावलोकन",
  "day_book": "डे बुक",
  "follow_ups": "फॉलो-अप",
  "cheque_mgmt": "चेक व्यवस्थापन",
  "gst_compliance": "अनुपालन",
  "balance_sheet": "बॅलन्स शीट",
  "master_data": "मास्टर डेटा",
  "crate_types": "क्रेट प्रकार",
  "customers_vendors": "ग्राहक आणि विक्रेते",
  "banks": "बँका",
  "employees": "कर्मचारी",
  "settings": "सेटिंग्ज",
  "logout": "लॉग आउट",
  "language": "भाषा निवडा"
};

const gu = {
  ...en,
  "dashboard": "ડેશબોર્ડ",
  "purchase": "ખરીદી",
  "mandi_commission": "ખરીદી + વેચાણ",
  "gate_entry": "ગેટ એન્ટ્રી",
  "arrivals": "આગમન (ઇનવર્ડ)",
  "purchase_bills": "ખરીદી બિલ",
  "sales": "વેચાણ અને બિલિંગ",
  "sale_invoice": "વેચાણ ઇન્વૉઇસ",
  "bulk_lot_sale": "જથ્થાબંધ લોટ વેચાણ",
  "inventory": "સ્ટોકની સ્થિતિ",
  "commodity_master": "કોમોડિટી માસ્ટર",
  "stock_status": "સ્ટોકની સ્થિતિ",
  "payments_receipts": "ચુકવણી અને રસીદો",
  "trading_pl": "ટ્રેડિંગ નફો/નુકસાન",
  "finance": "નાણાં",
  "finance_overview": "નાણાં વિહંગાવલોકન",
  "day_book": "ડે બુક",
  "follow_ups": "ફોલો-અપ્સ",
  "cheque_mgmt": "ચેક મેનેજમેન્ટ",
  "gst_compliance": "અનુપાલન",
  "balance_sheet": "સરવૈયુ",
  "master_data": "માસ્ટર ડેટા",
  "crate_types": "ક્રેટ પ્રકારો",
  "customers_vendors": "ગ્રાહકો અને વિક્રેતાઓ",
  "banks": "બેંકો",
  "employees": "કર્મચારીઓ",
  "settings": "સેટિંગ્સ",
  "logout": "લૉગઆઉટ",
  "language": "ભાષા પસંદ કરો"
};

const ta = {
  ...en,
  "dashboard": "முகப்புப் பக்கம்",
  "purchase": "கொள்முதல்",
  "mandi_commission": "கொள்முதல் + விற்பனை",
  "gate_entry": "கேட் என்ட்ரி",
  "arrivals": "வரத்து (உள்வரும்)",
  "purchase_bills": "கொள்முதல் பில்கள்",
  "sales": "விற்பனை & பில்லிங்",
  "sale_invoice": "விற்பனை விலைப்பட்டியல்",
  "bulk_lot_sale": "மொத்த லாட் விற்பனை",
  "inventory": "சரக்கு நிலை",
  "commodity_master": "பொருள் மாஸ்டர்",
  "stock_status": "சரக்கு நிலை",
  "payments_receipts": "கொடுப்பனவுகள் & ரசீதுகள்",
  "trading_pl": "வர்த்தக லாபம்/நஷ்டம்",
  "finance": "நிதி",
  "finance_overview": "நிதி கண்ணோட்டம்",
  "day_book": "டே புக்",
  "follow_ups": "பின்தொடர்தல்கள்",
  "cheque_mgmt": "காசோலை மேலாண்மை",
  "gst_compliance": "இணக்கம்",
  "balance_sheet": "இருப்பு தாள்",
  "master_data": "முதன்மை தரவு",
  "crate_types": "கிரேட் வகைகள்",
  "customers_vendors": "வாடிக்கையாளர்கள் & விற்பனையாளர்கள்",
  "banks": "வங்கிகள்",
  "employees": "பணியாளர்கள்",
  "settings": "அமைப்புகள்",
  "logout": "வெளியேறு",
  "language": "மொழியைத் தேர்ந்தெடு"
};

const kn = {
  ...en,
  "dashboard": "ಮುಖಪುಟ",
  "purchase": "ಖರೀದಿ",
  "mandi_commission": "ಖರೀದಿ + ಮಾರಾಟ",
  "gate_entry": "ಗೇಟ್ ಎಂಟ್ರಿ",
  "arrivals": "ಆಗಮನ (ಒಳಬರುವಿಕೆ)",
  "purchase_bills": "ಖರೀದಿ ಬಿಲ್‌ಗಳು",
  "sales": "ಮಾರಾಟ ಮತ್ತು ಬಿಲ್ಲಿಂಗ್",
  "sale_invoice": "ಮಾರಾಟ ಇನ್‌ವಾಯ್ಸ್",
  "bulk_lot_sale": "ಬಲ್ಕ್ ಲಾಟ್ ಮಾರಾಟ",
  "inventory": "ಸ್ಟಾಕ್ ಸ್ಥಿತಿ",
  "commodity_master": "ಕಮಾಡಿಟಿ ಮಾಸ್ಟರ್",
  "stock_status": "ಸ್ಟಾಕ್ ಸ್ಥಿತಿ",
  "payments_receipts": "ಪಾವತಿಗಳು ಮತ್ತು ರಸೀದಿಗಳು",
  "trading_pl": "ವ್ಯಾಪಾರ ಲಾಭ/ನಷ್ಟ",
  "finance": "ಹಣಕಾಸು",
  "finance_overview": "ಹಣಕಾಸು ಅವಲೋಕನ",
  "day_book": "ಡೇ ಬುಕ್",
  "follow_ups": "ಫಾಲೋ-ಅಪ್‌ಗಳು",
  "cheque_mgmt": "ಚೆಕ್ ನಿರ್ವಹಣೆ",
  "gst_compliance": "ಅನುವರ್ತನೆ",
  "balance_sheet": "ಬ್ಯಾಲೆನ್ಸ್ ಶೀಟ್",
  "master_data": "ಮಾಸ್ಟರ್ ಡೇಟಾ",
  "crate_types": "ಕ್ರೇಟ್ ಪ್ರಕಾರಗಳು",
  "customers_vendors": "ಗ್ರಾಹಕರು ಮತ್ತು ಮಾರಾಟಗಾರರು",
  "banks": "ಬ್ಯಾಂಕುಗಳು",
  "employees": "ಉದ್ಯೋಗಿಗಳು",
  "settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  "logout": "ಲಾಗ್ ಔಟ್",
  "language": "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ"
};

const ml = {
  ...en,
  "dashboard": "ഡാഷ്‌ബോർഡ്",
  "purchase": "പർച്ചേസ്",
  "mandi_commission": "പർച്ചേസ് + വിൽപ്പന",
  "gate_entry": "ഗേറ്റ് എൻട്രി",
  "arrivals": "വരവുകൾ (ഇൻവേർഡ്)",
  "purchase_bills": "പർച്ചേസ് ബില്ലുകൾ",
  "sales": "വിൽപ്പന & ബില്ലിംഗ്",
  "sale_invoice": "വിൽപ്പന ഇൻവോയ്സ്",
  "bulk_lot_sale": "ബൾക്ക് ലോട്ട് വിൽപ്പന",
  "inventory": "സ്റ്റോക്ക് നില",
  "commodity_master": "കമ്മോഡിറ്റി മാസ്റ്റർ",
  "stock_status": "സ്റ്റോക്ക് നില",
  "payments_receipts": "പേയ്‌മെന്റുകൾ & രസീതുകൾ",
  "trading_pl": "ട്രേഡിംഗ് ലാഭം/നഷ്ടം",
  "finance": "സാമ്പത്തികം",
  "finance_overview": "സാമ്പത്തിക അവലോകനം",
  "day_book": "ഡേ ബുക്ക്",
  "follow_ups": "ഫോളോ-അപ്പുകൾ",
  "cheque_mgmt": "ചെക്ക് മാനേജ്മെന്റ്",
  "gst_compliance": "കംപ്ലയൻസ്",
  "balance_sheet": "ബാലൻസ് ഷീറ്റ്",
  "master_data": "മാസ്റ്റർ ഡാറ്റ",
  "crate_types": "ക്രേറ്റ് തരങ്ങൾ",
  "customers_vendors": "ഉപഭോക്താക്കൾ & വെണ്ടർമാർ",
  "banks": "ബാങ്കുകൾ",
  "employees": "ജീവനക്കാർ",
  "settings": "ക്രമീകരണങ്ങൾ",
  "logout": "ലോഗ്ഔട്ട്",
  "language": "ഭാഷ തിരഞ്ഞെടുക്കുക"
};

const ur = {
  ...en,
  "dashboard": "ڈیش بورڈ",
  "purchase": "خریداری",
  "mandi_commission": "خرید + فروخت",
  "gate_entry": "گیٹ انٹری",
  "arrivals": "آمد (انورڈ)",
  "purchase_bills": "خریداری کے بل",
  "sales": "فروخت اور بلنگ",
  "sale_invoice": "فروخت کی رسید",
  "bulk_lot_sale": "بلک لاٹ سیل",
  "inventory": "اسٹاک کی صورتحال",
  "commodity_master": "کموڈٹی ماسٹر",
  "stock_status": "اسٹاک کی صورتحال",
  "payments_receipts": "ادائیگیاں اور رسیدیں",
  "trading_pl": "تجارتی نفع/نقصان",
  "finance": "مالیات",
  "finance_overview": "مالیاتی جائزہ",
  "day_book": "ڈے بک",
  "follow_ups": "فالو اپس",
  "cheque_mgmt": "چیک کا انتظام",
  "gst_compliance": "تعمیل",
  "balance_sheet": "بیلنس شیٹ",
  "master_data": "ماسٹر ڈیٹا",
  "crate_types": "کریٹ کی اقسام",
  "customers_vendors": "صارفین اور فروخت کنندگان",
  "banks": "بینک",
  "employees": "ملازمین",
  "settings": "ترتیبات",
  "logout": "لاگ آؤٹ",
  "language": "زبان منتخب کریں"
};

const translations = { en, hi, mr, gu, ta, kn, ml, ur };

for (const [lang, navData] of Object.entries(translations)) {
  const targetFile = path.join(localesDir, lang, 'common.json');
  if (fs.existsSync(targetFile)) {
    const data = JSON.parse(fs.readFileSync(targetFile, 'utf8'));
    if (!data.nav) {
      data.nav = {};
    }
    // Overwrite the nav object entirely with our complete mapping to ensure consistency
    data.nav = { ...data.nav, ...navData };
    fs.writeFileSync(targetFile, JSON.stringify(data, null, 2), 'utf8');
    console.log(`Updated complete nav for ${lang}`);
  }
}
