export const FOOTER_COLUMNS = [
    {
        heading: 'Product',
        links: [
            { label: 'Features',           href: '/features' },
            { label: 'Pricing',            href: '/pricing' },
            { label: 'HSN & GST Finder',   href: '/hsn-gst-rates-mandi-commodities' },
            { label: 'Blog',               href: '/blog' },
            { label: 'Mandi Billing',      href: '/mandi-billing' },
            { label: 'Mandi ERP',          href: '/mandi-erp-software' },
            { label: 'Commission Agent',   href: '/commission-agent-software' },
            { label: 'Digital Khata',      href: '/digital-mandi-khata-software' },
            { label: 'Mandi Accounting',   href: '/mandi-accounting-software' },
            { label: 'J-Form Billing',     href: '/j-form-billing-software' },
            { label: 'APMC Gate Pass',     href: '/apmc-gate-pass-software' },
            { label: 'GST Compliance',     href: '/gst-mandi-compliance' },
            { label: 'Mandi Billing Software', href: '/mandi-billing-software' },
            { label: 'Mandi Khata App',    href: '/mandi-khata-software' },
            { label: 'Crate Tracking',     href: '/mandi-crate-management-software' },
            { label: 'Farmer Payments',    href: '/farmer-payment-management' },
            { label: 'Best Mandi Software in India', href: '/best-mandi-software-in-india' },
            { label: 'Hardware Integration', href: '/weighbridge-barcode-integration-mandi-software' },
        ],
    },
    {
        heading: 'By Commodity',
        links: [
            { label: 'Fruit Mandi',           href: '/fruit-mandi-software' },
            { label: 'Sabji / Vegetable',     href: '/sabji-mandi-software' },
            { label: 'Apple Mandi',           href: '/apple-mandi-software' },
            { label: 'Mango Mandi',           href: '/mango-mandi-software' },
            { label: 'Onion & Potato',        href: '/onion-potato-mandi-software' },
            { label: 'Mirchi Mandi',          href: '/chilli-mandi-software' },
            { label: 'Tomato Mandi',          href: '/tomato-mandi-software' },
            { label: 'Anaj / Grain',          href: '/anaj-mandi-erp-software' },
            { label: 'Poultry Wholesale',     href: '/poultry-wholesale-software' },
            { label: 'Sabji Crate App',       href: '/sabji-crate-management-app' },
        ],
    },
    {
        heading: 'By State',
        links: [
            { label: 'Andhra Pradesh',   href: '/mandi-software-andhra-pradesh' },
            { label: 'Telangana',        href: '/mandi-software-telangana' },
            { label: 'Maharashtra',      href: '/mandi-software-maharashtra' },
            { label: 'Punjab',           href: '/mandi-software-punjab' },
            { label: 'Karnataka',        href: '/mandi-software-karnataka' },
            { label: 'Tamil Nadu',       href: '/mandi-software-tamil-nadu' },
            { label: 'Rajasthan',        href: '/mandi-software-rajasthan' },
            { label: 'Uttar Pradesh',    href: '/mandi-software-uttar-pradesh' },
            { label: 'In Hindi',         href: '/mandi-software-hindi' },
            { label: 'In Marathi',       href: '/mandi-software-marathi' },
        ],
    },
    {
        heading: 'By City',
        links: [
            { label: 'Azadpur Mandi',       href: '/azadpur-mandi-software' },
            { label: 'Vashi Mandi',         href: '/vashi-mandi-software' },
            { label: 'Ghazipur Mandi',      href: '/ghazipur-mandi-software' },
            { label: 'Yeshwanthpur',        href: '/yeshwanthpur-mandi-software' },
            { label: 'Bowenpally',          href: '/bowenpally-mandi-software' },
            { label: 'Okhla Mandi',         href: '/okhla-mandi-software' },
            { label: 'Ahmedabad',           href: '/mandi-software-ahmedabad' },
            { label: 'Bangalore',           href: '/mandi-software-bangalore' },
            { label: 'Indore',              href: '/mandi-software-indore' },
            { label: 'Pune',                href: '/mandi-software-pune' },
            { label: 'Nashik',              href: '/mandi-software-nashik' },
        ],
    },
    {
        heading: 'Compare',
        links: [
            { label: 'MandiGrow vs Tally',    href: '/tally-vs-mandigrow' },
            { label: 'MandiGrow vs Vyapar',   href: '/vyapar-vs-mandigrow' },
            { label: 'MandiGrow vs Marg ERP', href: '/marg-erp-vs-mandigrow' },
            { label: 'MandiGrow vs Zoho',     href: '/zoho-vs-mandigrow' },
        ],
    },
    {
        heading: 'Company',
        links: [
            { label: 'About Us',       href: '/about' },
            { label: 'Blog',           href: '/blog' },
            { label: 'FAQ',            href: '/faq' },
            { label: 'Partners',       href: '/partners' },
            { label: 'Contact',        href: '/contact' },
            { label: 'Privacy Policy', href: '/privacy' },
            { label: 'Terms of Service', href: '/terms' },
            { label: 'Refund Policy',  href: '/refund-policy' },
        ],
    },
];
