import type { MetadataRoute } from 'next';

const BASE_URL = 'https://www.mandigrow.com';

export default function robots(): MetadataRoute.Robots {
    return {
        rules: [
            {
                userAgent: '*',
                allow: [
                    '/',
                    '/mandi-billing',
                    '/commission-agent-software',
                    '/mandi-khata-software',
                    '/wholesale-trader-erp',
                    '/gst-mandi-compliance',
                    '/sabzi-mandi-software',
                    '/sabji-billing-software',
                    '/fruit-vegetable-billing',
                    '/mandi-software-andhra-pradesh',
                    '/mandi-software-maharashtra',
                    '/mandi-software-telangana',
                    '/mandi-software-hyderabad',
                    '/mandi-software-guntur',
                    '/mandi-software-nashik',
                    '/mandi-software-delhi',
                    '/mandi-software-pune',
                    '/fruit-trader-software',
                    '/vegetable-market-software',
                    '/warehouse-management-mandi',
                    '/gst-billing-for-arhtiyas',
                    '/auction-management-software',
                    '/farmer-payment-management',
                    '/inventory-management-mandi',
                    '/faq',
                    '/blog',
                    '/login',
                    '/subscribe',
                    '/join',
                    '/contact',
                ],
                disallow: [
                    '/admin',
                    '/api',
                    '/auth',
                    '/checkout',
                    '/dashboard',
                    '/sales',
                    '/arrivals',
                    '/finance',
                    '/settings',
                    '/reports',
                    '/inventory',
                    '/purchase',
                    '/ledgers',
                    '/contacts',
                    '/farmers',
                    '/buyers',
                    '/employees',
                    '/gate',
                    '/gate-logs',
                    '/auction',
                    '/auction-live',
                    '/bills',
                    '/quotations',
                    '/receipts',
                    '/credit-notes',
                    '/delivery-challans',
                    '/sales-orders',
                    '/price-lists',
                    '/accounting',
                    '/field-manager',
                    '/suspended',
                    '/seed',
                ],
            },
        ],
        sitemap: `${BASE_URL}/sitemap.xml`,
        host: BASE_URL,
    };
}
