// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(main)/accounting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounting">> = Specific
  const handler = {} as typeof import("../../../app/(main)/accounting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/admin/billing/renewal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing/renewal">> = Specific
  const handler = {} as typeof import("../../../app/(main)/admin/billing/renewal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/arrivals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/arrivals">> = Specific
  const handler = {} as typeof import("../../../app/(main)/arrivals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/auction-live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auction-live">> = Specific
  const handler = {} as typeof import("../../../app/(main)/auction-live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/auction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auction">> = Specific
  const handler = {} as typeof import("../../../app/(main)/auction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/bills/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bills/create">> = Specific
  const handler = {} as typeof import("../../../app/(main)/bills/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bills">> = Specific
  const handler = {} as typeof import("../../../app/(main)/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/buyers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buyers">> = Specific
  const handler = {} as typeof import("../../../app/(main)/buyers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacts">> = Specific
  const handler = {} as typeof import("../../../app/(main)/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/credit-notes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credit-notes/new">> = Specific
  const handler = {} as typeof import("../../../app/(main)/credit-notes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/credit-notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credit-notes">> = Specific
  const handler = {} as typeof import("../../../app/(main)/credit-notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(main)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/delivery-challans/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery-challans/new">> = Specific
  const handler = {} as typeof import("../../../app/(main)/delivery-challans/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/delivery-challans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery-challans">> = Specific
  const handler = {} as typeof import("../../../app/(main)/delivery-challans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employees">> = Specific
  const handler = {} as typeof import("../../../app/(main)/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/farmers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/farmers">> = Specific
  const handler = {} as typeof import("../../../app/(main)/farmers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/field-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/field-manager">> = Specific
  const handler = {} as typeof import("../../../app/(main)/field-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/finance/daily-rate-fixer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/daily-rate-fixer">> = Specific
  const handler = {} as typeof import("../../../app/(main)/finance/daily-rate-fixer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/finance/farmer-settlements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/farmer-settlements">> = Specific
  const handler = {} as typeof import("../../../app/(main)/finance/farmer-settlements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../../app/(main)/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/finance/patti/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/patti/new">> = Specific
  const handler = {} as typeof import("../../../app/(main)/finance/patti/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/finance/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payments">> = Specific
  const handler = {} as typeof import("../../../app/(main)/finance/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/finance/reconciliation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/reconciliation">> = Specific
  const handler = {} as typeof import("../../../app/(main)/finance/reconciliation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/finance/reminders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/reminders">> = Specific
  const handler = {} as typeof import("../../../app/(main)/finance/reminders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/gate-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gate-logs">> = Specific
  const handler = {} as typeof import("../../../app/(main)/gate-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/gate/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gate/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/gate/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/gate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gate">> = Specific
  const handler = {} as typeof import("../../../app/(main)/gate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/inventory/items/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/items">> = Specific
  const handler = {} as typeof import("../../../app/(main)/inventory/items/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/inventory/storage-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/storage-map">> = Specific
  const handler = {} as typeof import("../../../app/(main)/inventory/storage-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/ledgers/buyer/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ledgers/buyer/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/ledgers/buyer/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/ledgers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ledgers">> = Specific
  const handler = {} as typeof import("../../../app/(main)/ledgers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/mandi-commission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mandi-commission">> = Specific
  const handler = {} as typeof import("../../../app/(main)/mandi-commission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific
  const handler = {} as typeof import("../../../app/(main)/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/price-lists/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/price-lists">> = Specific
  const handler = {} as typeof import("../../../app/(main)/price-lists/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/purchase/bills/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/bills/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/purchase/bills/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/purchase/bills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/bills">> = Specific
  const handler = {} as typeof import("../../../app/(main)/purchase/bills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/purchase/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase/invoices">> = Specific
  const handler = {} as typeof import("../../../app/(main)/purchase/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/quotations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotations">> = Specific
  const handler = {} as typeof import("../../../app/(main)/quotations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/receipts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/receipts">> = Specific
  const handler = {} as typeof import("../../../app/(main)/receipts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/balance-sheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/balance-sheet">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/balance-sheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/daybook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/daybook">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/daybook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/gst/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/gst">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/gst/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/ledger">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/margins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/margins">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/margins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/pl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/pl">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/pl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/price-forecast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/price-forecast">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/price-forecast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/reports/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/stock">> = Specific
  const handler = {} as typeof import("../../../app/(main)/reports/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-orders/new">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-orders">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/bulk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/bulk">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/bulk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/challan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/challan">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/challan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/new-invoice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/new-invoice">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/new-invoice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/new">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/orders">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/pos">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/return/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/return/new">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/return/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/sales/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/returns">> = Specific
  const handler = {} as typeof import("../../../app/(main)/sales/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/bank-details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/bank-details">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/bank-details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/banks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/banks">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/banks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/billing/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/billing/checkout">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/billing/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/billing">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/billing/payment-callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/billing/payment-callback">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/billing/payment-callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/branding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/branding">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/branding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/compliance">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/feature-flags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/feature-flags">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/feature-flags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/fields/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/fields">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/fields/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/settings/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/team">> = Specific
  const handler = {} as typeof import("../../../app/(main)/settings/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock">> = Specific
  const handler = {} as typeof import("../../../app/(main)/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/stock/quick-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock/quick-entry">> = Specific
  const handler = {} as typeof import("../../../app/(main)/stock/quick-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse">> = Specific
  const handler = {} as typeof import("../../../app/(main)/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/admins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/admins">> = Specific
  const handler = {} as typeof import("../../../app/admin/admins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../../app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../../app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/billing/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing/coupons">> = Specific
  const handler = {} as typeof import("../../../app/admin/billing/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/billing/gateways/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing/gateways">> = Specific
  const handler = {} as typeof import("../../../app/admin/billing/gateways/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing">> = Specific
  const handler = {} as typeof import("../../../app/admin/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/billing/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing/plans">> = Specific
  const handler = {} as typeof import("../../../app/admin/billing/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/contact-info/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contact-info">> = Specific
  const handler = {} as typeof import("../../../app/admin/contact-info/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/features">> = Specific
  const handler = {} as typeof import("../../../app/admin/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/multi-mandi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/multi-mandi">> = Specific
  const handler = {} as typeof import("../../../app/admin/multi-mandi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/partners">> = Specific
  const handler = {} as typeof import("../../../app/admin/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payouts">> = Specific
  const handler = {} as typeof import("../../../app/admin/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sessions">> = Specific
  const handler = {} as typeof import("../../../app/admin/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/partners">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/settings/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/payments">> = Specific
  const handler = {} as typeof import("../../../app/admin/settings/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../../app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/tenant-health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenant-health">> = Specific
  const handler = {} as typeof import("../../../app/admin/tenant-health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/tenants/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenants/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/tenants/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/tenants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenants">> = Specific
  const handler = {} as typeof import("../../../app/admin/tenants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/webhooks">> = Specific
  const handler = {} as typeof import("../../../app/admin/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/commission-agent-software/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/commission-agent-software">> = Specific
  const handler = {} as typeof import("../../../app/commission-agent-software/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/features">> = Specific
  const handler = {} as typeof import("../../../app/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/fruit-vegetable-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fruit-vegetable-billing">> = Specific
  const handler = {} as typeof import("../../../app/fruit-vegetable-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/gst-mandi-compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gst-mandi-compliance">> = Specific
  const handler = {} as typeof import("../../../app/gst-mandi-compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join">> = Specific
  const handler = {} as typeof import("../../../app/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mandi-billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mandi-billing">> = Specific
  const handler = {} as typeof import("../../../app/mandi-billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mandi-khata-software/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mandi-khata-software">> = Specific
  const handler = {} as typeof import("../../../app/mandi-khata-software/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mandi-software-andhra-pradesh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mandi-software-andhra-pradesh">> = Specific
  const handler = {} as typeof import("../../../app/mandi-software-andhra-pradesh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mandi-software-maharashtra/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mandi-software-maharashtra">> = Specific
  const handler = {} as typeof import("../../../app/mandi-software-maharashtra/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/mandi-software-telangana/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mandi-software-telangana">> = Specific
  const handler = {} as typeof import("../../../app/mandi-software-telangana/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partner-portal/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner-portal/login">> = Specific
  const handler = {} as typeof import("../../../app/partner-portal/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partner-portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner-portal">> = Specific
  const handler = {} as typeof import("../../../app/partner-portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../../app/partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/public/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/public/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../../app/public/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../../app/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sabji-billing-software/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sabji-billing-software">> = Specific
  const handler = {} as typeof import("../../../app/sabji-billing-software/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/sabzi-mandi-software/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sabzi-mandi-software">> = Specific
  const handler = {} as typeof import("../../../app/sabzi-mandi-software/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/seed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seed">> = Specific
  const handler = {} as typeof import("../../../app/seed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/provisioning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/provisioning">> = Specific
  const handler = {} as typeof import("../../../app/signup/provisioning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/signup/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/verify">> = Specific
  const handler = {} as typeof import("../../../app/signup/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/subscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscribe">> = Specific
  const handler = {} as typeof import("../../../app/subscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/suspended/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suspended">> = Specific
  const handler = {} as typeof import("../../../app/suspended/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/te/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/te">> = Specific
  const handler = {} as typeof import("../../../app/te/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/wholesale-trader-erp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/wholesale-trader-erp">> = Specific
  const handler = {} as typeof import("../../../app/wholesale-trader-erp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/admins/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/admins/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/admins/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/admins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/admins">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/admins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/actions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/activate-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/activate-plan">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/activate-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/custom-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/custom-plan">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/custom-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/gateways/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/gateways">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/gateways/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/invoice-preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/invoice-preview">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/invoice-preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/invoices">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/plans/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/plans">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/plans/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/renew/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/renew">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/renew/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/billing/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/billing/subscription">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/billing/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/coupons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/coupons">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/coupons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/create-mandi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-mandi">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/create-mandi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/create-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/create-user">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/create-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/delete-employee/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/delete-employee">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/delete-employee/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/delete-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/delete-user">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/delete-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/impersonate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/impersonate">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/impersonate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/lifecycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/lifecycle">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/lifecycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/metrics">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/monitoring/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/monitoring">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/monitoring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/payments/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/payments/config">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/payments/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/provision/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/provision">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/provision/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reset-mrr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset-mrr">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reset-mrr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sessions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/support">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/tenants/[id]/assign-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tenants/[id]/assign-plan">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/tenants/[id]/assign-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/tenants/[id]/extend-trial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tenants/[id]/extend-trial">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/tenants/[id]/extend-trial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/tenants/[id]/owner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tenants/[id]/owner">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/tenants/[id]/owner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/tenants/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tenants/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/tenants/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/tenants/[id]/users/[userId]/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tenants/[id]/users/[userId]/permissions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/tenants/[id]/users/[userId]/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/tenants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tenants">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/tenants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/update-permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/update-permissions">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/update-permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/check-unique/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check-unique">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/check-unique/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/lookup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/lookup">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/lookup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/new-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/new-session">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/new-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/record-consent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/record-consent">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/record-consent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/activate">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/coupon-validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/coupon-validate">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/coupon-validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/dunning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/dunning">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/dunning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/init-bucket/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/init-bucket">> = Specific
  const handler = {} as typeof import("../../../app/api/init-bucket/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/arrivals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/arrivals/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/arrivals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/arrivals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/arrivals">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/arrivals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/field-governance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/field-governance">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/field-governance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/reports/daybook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/reports/daybook">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/reports/daybook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/reports/pnl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/reports/pnl">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/reports/pnl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/sales/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/sales/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/sales/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/sales">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/mandi/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mandi/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/mandi/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/organization/check-limit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/organization/check-limit">> = Specific
  const handler = {} as typeof import("../../../app/api/organization/check-limit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/parse-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse-pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/parse-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/parse-xls/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse-xls">> = Specific
  const handler = {} as typeof import("../../../app/api/parse-xls/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/partner-apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-apply">> = Specific
  const handler = {} as typeof import("../../../app/api/partner-apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/smepay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/smepay">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/smepay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/payments/smepay/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payments/smepay/status">> = Specific
  const handler = {} as typeof import("../../../app/api/payments/smepay/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/public/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/signup">> = Specific
  const handler = {} as typeof import("../../../app/api/public/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/repair-alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repair-alerts">> = Specific
  const handler = {} as typeof import("../../../app/api/repair-alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed">> = Specific
  const handler = {} as typeof import("../../../app/api/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/branding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/branding">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/branding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/subscription/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/subscription/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/subscription/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/current">> = Specific
  const handler = {} as typeof import("../../../app/api/subscription/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/subscription/downgrade/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/downgrade">> = Specific
  const handler = {} as typeof import("../../../app/api/subscription/downgrade/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/razorpay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/razorpay">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/razorpay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/smepay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/smepay">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/smepay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../../app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/whatsapp">> = Specific
  const handler = {} as typeof import("../../../app/api/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partner-portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partner-portal">> = Specific
  const handler = {} as typeof import("../../../app/partner-portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/partners/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/partners">> = Specific
  const handler = {} as typeof import("../../../app/partners/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
